# Generated by Django 5.1.3 on 2024-12-03 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0002_create_fundraiser_personal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='create_fundraiser_personal',
        ),
    ]
